services:
    postgres:
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - '3001:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data